import {LeaderboardEntry} from '../types/leaderboard';
import {getReadableStringFromScore, getLeadersFromLeaderboard, getLeadersAsReadableString} from './golf';

const leaderboard: LeaderboardEntry[] = [
    {
        id: 'a7041051-eb25-40b9-acb3-dab88cae69c0',
        first_name: 'Dustin',
        last_name: 'Johnson',
        country: 'UNITED STATES',
        position: 1,
        tied: false,
        money: 2070000,
        points: 600,
        score: -20,
        strokes: 268,
        abbr_name: 'D.Johnson',
        rounds: [
            {
                score: -7,
                strokes: 65,
                thru: 18,
                eagles: 1,
                birdies: 5,
                pars: 12,
                bogeys: 0,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 1,
            },
            {
                score: -2,
                strokes: 70,
                thru: 18,
                eagles: 0,
                birdies: 4,
                pars: 12,
                bogeys: 2,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 2,
            },
            {
                score: -7,
                strokes: 65,
                thru: 18,
                eagles: 1,
                birdies: 5,
                pars: 12,
                bogeys: 0,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 3,
            },
            {
                score: -4,
                strokes: 68,
                thru: 18,
                eagles: 0,
                birdies: 6,
                pars: 10,
                bogeys: 2,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 4,
            },
        ],
    },
    {
        id: 'aee6ead9-10e0-445b-aa13-d037cc1dd861',
        first_name: 'Cameron',
        last_name: 'Smith',
        country: 'AUSTRALIA',
        position: 2,
        tied: true,
        money: 1012000,
        points: 270,
        score: -15,
        strokes: 273,
        abbr_name: 'C.Smith',
        rounds: [
            {
                score: -5,
                strokes: 67,
                thru: 18,
                eagles: 0,
                birdies: 6,
                pars: 11,
                bogeys: 1,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 1,
            },
            {
                score: -4,
                strokes: 68,
                thru: 18,
                eagles: 1,
                birdies: 6,
                pars: 7,
                bogeys: 4,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 2,
            },
            {
                score: -3,
                strokes: 69,
                thru: 18,
                eagles: 0,
                birdies: 3,
                pars: 15,
                bogeys: 0,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 3,
            },
            {
                score: -3,
                strokes: 69,
                thru: 18,
                eagles: 0,
                birdies: 5,
                pars: 11,
                bogeys: 2,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 4,
            },
        ],
    },
    {
        id: 'ac1db384-8cb4-4223-bc46-60f4ed963645',
        first_name: 'Sungjae',
        last_name: 'Im',
        country: 'SOUTH KOREA',
        position: 2,
        tied: true,
        money: 1012000,
        points: 270,
        score: -15,
        strokes: 273,
        abbr_name: 'S.Im',
        rounds: [
            {
                score: -6,
                strokes: 66,
                thru: 18,
                eagles: 0,
                birdies: 8,
                pars: 8,
                bogeys: 2,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 1,
            },
            {
                score: -2,
                strokes: 70,
                thru: 18,
                eagles: 0,
                birdies: 6,
                pars: 8,
                bogeys: 4,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 2,
            },
            {
                score: -4,
                strokes: 68,
                thru: 18,
                eagles: 0,
                birdies: 5,
                pars: 12,
                bogeys: 1,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 3,
            },
            {
                score: -3,
                strokes: 69,
                thru: 18,
                eagles: 0,
                birdies: 5,
                pars: 11,
                bogeys: 2,
                double_bogeys: 0,
                other_scores: 0,
                holes_in_one: 0,
                sequence: 4,
            },
        ],
    },
];

describe('Get voice readable string from score', () => {
    test('it should correctly return a score under par', () => {
        expect(getReadableStringFromScore(-5)).toEqual('<sub alias="five under">-5</sub>');
        expect(getReadableStringFromScore(-26)).toEqual('<sub alias="twenty six under">-26</sub>');
    });

    test('it should correctly return a score over par', () => {
        expect(getReadableStringFromScore(5)).toEqual('<sub alias="five over">+5</sub>');
        expect(getReadableStringFromScore(26)).toEqual('<sub alias="twenty six over">+26</sub>');
    });

    test('it should correctly return a score of even par', () => {
        expect(getReadableStringFromScore(0)).toEqual('<sub alias="even par">E</sub>');
    });
});

describe('Get leaders from leaderboard', () => {
    test('Should get single leader if there is no tie', () => {
        expect(getLeadersFromLeaderboard(leaderboard)).toEqual([
            {
                id: 'a7041051-eb25-40b9-acb3-dab88cae69c0',
                first_name: 'Dustin',
                last_name: 'Johnson',
                country: 'UNITED STATES',
                position: 1,
                tied: false,
                money: 2070000,
                points: 600,
                score: -20,
                strokes: 268,
                abbr_name: 'D.Johnson',
                rounds: [
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -2,
                        strokes: 70,
                        thru: 18,
                        eagles: 0,
                        birdies: 4,
                        pars: 12,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 10,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
        ]);
    });

    test('Should get 2 leaders if there is a 2 way tie', () => {
        expect(getLeadersFromLeaderboard([leaderboard[0], {...leaderboard[1], position: 1}, leaderboard[2]])).toEqual([
            {
                id: 'a7041051-eb25-40b9-acb3-dab88cae69c0',
                first_name: 'Dustin',
                last_name: 'Johnson',
                country: 'UNITED STATES',
                position: 1,
                tied: false,
                money: 2070000,
                points: 600,
                score: -20,
                strokes: 268,
                abbr_name: 'D.Johnson',
                rounds: [
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -2,
                        strokes: 70,
                        thru: 18,
                        eagles: 0,
                        birdies: 4,
                        pars: 12,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 10,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
            {
                id: 'aee6ead9-10e0-445b-aa13-d037cc1dd861',
                first_name: 'Cameron',
                last_name: 'Smith',
                country: 'AUSTRALIA',
                position: 1,
                tied: true,
                money: 1012000,
                points: 270,
                score: -15,
                strokes: 273,
                abbr_name: 'C.Smith',
                rounds: [
                    {
                        score: -5,
                        strokes: 67,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 11,
                        bogeys: 1,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 1,
                        birdies: 6,
                        pars: 7,
                        bogeys: 4,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -3,
                        strokes: 69,
                        thru: 18,
                        eagles: 0,
                        birdies: 3,
                        pars: 15,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -3,
                        strokes: 69,
                        thru: 18,
                        eagles: 0,
                        birdies: 5,
                        pars: 11,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
        ]);
    });

    test('Should get 3 leaders if there is a 3 way tie', () => {
        expect(
            getLeadersFromLeaderboard([
                leaderboard[0],
                {...leaderboard[1], position: 1},
                {...leaderboard[2], position: 1},
            ])
        ).toEqual([
            {
                id: 'a7041051-eb25-40b9-acb3-dab88cae69c0',
                first_name: 'Dustin',
                last_name: 'Johnson',
                country: 'UNITED STATES',
                position: 1,
                tied: false,
                money: 2070000,
                points: 600,
                score: -20,
                strokes: 268,
                abbr_name: 'D.Johnson',
                rounds: [
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -2,
                        strokes: 70,
                        thru: 18,
                        eagles: 0,
                        birdies: 4,
                        pars: 12,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -7,
                        strokes: 65,
                        thru: 18,
                        eagles: 1,
                        birdies: 5,
                        pars: 12,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 10,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
            {
                id: 'aee6ead9-10e0-445b-aa13-d037cc1dd861',
                first_name: 'Cameron',
                last_name: 'Smith',
                country: 'AUSTRALIA',
                position: 1,
                tied: true,
                money: 1012000,
                points: 270,
                score: -15,
                strokes: 273,
                abbr_name: 'C.Smith',
                rounds: [
                    {
                        score: -5,
                        strokes: 67,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 11,
                        bogeys: 1,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 1,
                        birdies: 6,
                        pars: 7,
                        bogeys: 4,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -3,
                        strokes: 69,
                        thru: 18,
                        eagles: 0,
                        birdies: 3,
                        pars: 15,
                        bogeys: 0,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -3,
                        strokes: 69,
                        thru: 18,
                        eagles: 0,
                        birdies: 5,
                        pars: 11,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
            {
                id: 'ac1db384-8cb4-4223-bc46-60f4ed963645',
                first_name: 'Sungjae',
                last_name: 'Im',
                country: 'SOUTH KOREA',
                position: 1,
                tied: true,
                money: 1012000,
                points: 270,
                score: -15,
                strokes: 273,
                abbr_name: 'S.Im',
                rounds: [
                    {
                        score: -6,
                        strokes: 66,
                        thru: 18,
                        eagles: 0,
                        birdies: 8,
                        pars: 8,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 1,
                    },
                    {
                        score: -2,
                        strokes: 70,
                        thru: 18,
                        eagles: 0,
                        birdies: 6,
                        pars: 8,
                        bogeys: 4,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 2,
                    },
                    {
                        score: -4,
                        strokes: 68,
                        thru: 18,
                        eagles: 0,
                        birdies: 5,
                        pars: 12,
                        bogeys: 1,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 3,
                    },
                    {
                        score: -3,
                        strokes: 69,
                        thru: 18,
                        eagles: 0,
                        birdies: 5,
                        pars: 11,
                        bogeys: 2,
                        double_bogeys: 0,
                        other_scores: 0,
                        holes_in_one: 0,
                        sequence: 4,
                    },
                ],
            },
        ]);
    });
});


describe('Get readable string from leaders', () => {
    test('Should get the single leader given a simple input', () => {
        expect(
            getLeadersAsReadableString([{first_name: 'Cameron', last_name: 'Smith', score: -34}], {
                roundInProgress: 4,
                anyRoundVariance: false,
            })
        ).toEqual(
            `The leader is currently Cameron Smith at ${getReadableStringFromScore(
                -34
            )}, after the <say-as interpret-as="ordinal">4</say-as> round.`
        );
    });

    test('Should get joint leaders given a simple input', () => {
        expect(
            getLeadersAsReadableString(
                [
                    {first_name: 'Cameron', last_name: 'Smith', score: -34},
                    {first_name: 'John', last_name: 'Rahm', score: -34},
                ],
                {
                    roundInProgress: 2,
                    anyRoundVariance: true,
                }
            )
        ).toEqual(
            `Cameron Smith and John Rahm are the joint leaders at ${getReadableStringFromScore(
                -34
            )}, during the <say-as interpret-as="ordinal">2</say-as> round.`
        );
    });

    test('Should get joint leaders given a complex input', () => {
        expect(
            getLeadersAsReadableString([leaderboard[0], leaderboard[1]], {anyRoundVariance: false, roundInProgress: 4})
        ).toEqual(
            `Dustin Johnson and Cameron Smith are the joint leaders at ${getReadableStringFromScore(
                -20
            )}, after the <say-as interpret-as="ordinal">4</say-as> round.`
        );
    });
});
