name: PR Checks

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test docker image
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t pro-golf-scores:latest . --target test
