name: PR Checks

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test docker image
        id: build-image
        run: |
          docker build -t pro-golf-scores:latest . --target test
          docker build -t pro-golf-scores:latest .
          docker run -p 10000:3000 pro-golf-scores:latest
          curl localhost:10000/health
