name: PR Checks

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test docker image
        id: build-image
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cat .npmrc
          docker build -t pro-golf-scores:latest . --target test
          docker build -t pro-golf-scores:latest .
          docker run -e DISABLE_LOGS=1 -d -p 10000:3000 pro-golf-scores:latest
      - name: Perform healthcheck
        run: |
          sleep 5
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" localhost:10000/health)
          if [ $STATUS_CODE -ne "200" ]; then echo "Healthcheck failed with code: $STATUS_CODE"; exit 1; fi
